# --------------------------------------------------------------------------------------------- #
# CONFIGURATION FILE
#
# This is an example of a configuration file allowing to customize the LLM & Diffuser API used
# by the app. Rename this file to "config.toml" in the root folder of the solution and set the
# variables below to their appropriate values.
# --------------------------------------------------------------------------------------------- #

# --------------------------------------------------------------------------------------------- #
# LLM
#
# This section corresponds to variables associated with the LLM, responsible for the automatic
# prompt improvements. behind the prompt operations.
# --------------------------------------------------------------------------------------------- #
[llm]
model_dir = "./models/llms"

# --------------------------------------------------------------------------------------------- #
# DIFFUSER
#
# This section corresponds to variables associated with the Diffusers, responsible for the
# text-to-image generation.
# --------------------------------------------------------------------------------------------- #
[diffuser]
model_dir = "./models/diffusers"

# --------------------------------------------------------------------------------------------- #
# OPTIMIZERS
#
# This section corresponds to variables associated with the prompt optimizers, responsible for the
# text-to-image generation.
# --------------------------------------------------------------------------------------------- #
[optimizer]
model_dir = "./prompting_rules"