# --------------------------------------------------------------------------------------------- #
# CONFIGURATION FILE
#
# This is an example of a configuration file allowing to customize the LLM & Diffuser API used
# by the app. Rename this file to "config.toml" in the root folder of the solution and set the
# variables below to their appropriate values.
# --------------------------------------------------------------------------------------------- #

# --------------------------------------------------------------------------------------------- #
# LLM
#
# This section corresponds to variables associated with the LLM, responsible for the automatic
# prompt improvements. behind the prompt operations.
# --------------------------------------------------------------------------------------------- #
[llm]
directory = "./models/llms"

# --------------------------------------------------------------------------------------------- #
# DIFFUSER
#
# This section corresponds to variables associated with the Diffusers, responsible for the
# text-to-image generation.
# --------------------------------------------------------------------------------------------- #
[diffuser]
directory = "./models/diffusers"

# --------------------------------------------------------------------------------------------- #
# POMPTING RULES
#
# This section corresponds to variables associated with the prompting rules followed when
# performing the prompt optimization step.
# --------------------------------------------------------------------------------------------- #
[prompting_rules]
directory = "./data/prompting_rules"